#include <stdio.h>
int main()
{
    printf("HELLO MY NAME IS SHAKIR,I'M FROM RAMANATTUKARA.MY FAMILY CONSIST OF 5 PERSONS.I'VE DONE MY DIPLOMA IN COMPUTER ENGINEERING AT AKNM POLYTECHNIC COLLEGE,CHELARI. CURRENTLY IAM STUDYING FLUTTER AS AN INTERN AT SOFTRONICS,CALICUT.I WANNA BECOME A FLUTTER DEVELOPER ONE DAY.I LIKE TO HANGOUT WITH FRIENDS AND WATCHING MOVIE SERIES.");
    return 0;
}